services:
  - type: web
    name: classproject
    runtime: python
    buildCommand: bash ./build.sh
    startCommand: gunicorn classproject.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DJANGO_SUPERUSER_USERNAME
        value: my_admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
